services:
  grok-auth-server:
    build:
      context: ./chat-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # MongoDB connection string
      MONGODB_URL: mongodb://admin:expatsSouthAfrica20@mongodb:27017/?authSource=admin
      MONGODB_DB_NAME: grok_chat
    depends_on:
      - mongodb
    volumes:
      - ./chat-backend:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb-crud
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: expatsSouthAfrica20
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: